"""Added constructor and driver standings

Revision ID: 84c6912a3cd3
Revises: 99865655966d
Create Date: 2025-08-17 15:03:53.058658

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84c6912a3cd3'
down_revision = '99865655966d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constructor_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('constructor_id', 'round_id', name='idx_constructor_standings_on_constructor_id_and_round_id')
    )
    op.create_table('driver_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'round_id', name='idx_driver_standings_on_driver_id_and_round_id')
    )

    with op.batch_alter_table('event_results', schema=None) as batch_op:
        batch_op.create_unique_constraint('idx_event_results_on_event_id_and_driver_id', ['event_id', 'driver_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_results', schema=None) as batch_op:
        batch_op.drop_constraint('idx_event_results_on_event_id_and_driver_id', type_='unique')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('permanent_number'), ['permanent_number'], unique=True)
        batch_op.create_index(batch_op.f('code'), ['code'], unique=True)

    op.create_table('races',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('season_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('circuit_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('race_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('round', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_sprint', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], name='races_ibfk_1'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name='races_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_season_round'), ['season_id', 'round'], unique=True)

    op.create_table('seasons',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('race_driver_results',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('race_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('driver_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('constructor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', mysql.FLOAT(), nullable=False),
    sa.Column('laps', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], name=op.f('race_driver_results_ibfk_1')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('race_driver_results_ibfk_2')),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('race_driver_results_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('driver_standings')
    op.drop_table('constructor_standings')
    # ### end Alembic commands ###
