"""Add adition attributes to  models

Revision ID: 9804944d689e
Revises: 9098093e1c8d
Create Date: 2025-08-02 16:55:22.894786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9804944d689e'
down_revision = '9098093e1c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circuits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('circuit_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False))
        batch_op.drop_column('country_emoji')

    with op.batch_alter_table('race_driver_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grid', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sprint', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_column('is_sprint')

    with op.batch_alter_table('race_driver_results', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('grid')

    with op.batch_alter_table('circuits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_emoji', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
        batch_op.drop_column('country')
        batch_op.drop_column('circuit_id')

    # ### end Alembic commands ###
