"""Added rounds table, removed seasons table, changed races to events

Revision ID: 99865655966d
Revises: 966a62029755
Create Date: 2025-08-17 14:44:25.130155

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99865655966d'
down_revision = '966a62029755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('race_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'round_number', name='idx_rounds_on_year_and_round_number')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'event_type', name='idx_events_on_round_id_and_event_type')
    )
    op.create_table('event_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('start_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.drop_table('race_driver_results')
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_season_round'))

    op.drop_table('races')
    op.drop_table('seasons')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('season_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('circuit_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('race_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('round', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_sprint', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], name='races_ibfk_1'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name='races_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_season_round'), ['season_id', 'round'], unique=True)

    op.create_table('race_driver_results',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('race_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('driver_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('constructor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', mysql.FLOAT(), nullable=False),
    sa.Column('laps', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], name=op.f('race_driver_results_ibfk_1')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('race_driver_results_ibfk_2')),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('race_driver_results_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('seasons',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('external_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('event_results')
    op.drop_table('events')
    op.drop_table('rounds')
    # ### end Alembic commands ###
