"""Add/refactor to external id in models

Revision ID: e5104f4a8e98
Revises: 9804944d689e
Create Date: 2025-08-02 18:34:19.452881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5104f4a8e98'
down_revision = '9804944d689e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circuits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=255), nullable=False))
        batch_op.drop_column('circuit_id')

    with op.batch_alter_table('constructors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=255), nullable=False))

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=255), nullable=False))

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.create_unique_constraint('idx_races_on_season_id_and_round', ['season_id', 'round'])

    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_constraint('uq_season_round', type_='unique')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('constructors', schema=None) as batch_op:
        batch_op.drop_column('external_id')

    with op.batch_alter_table('circuits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('circuit_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
